import React, { useState, useEffect } from 'react';
import Head from 'next/head';

import { makeStyles } from '@material-ui/core/styles';
import {
  Grid,
  Typography,
  Checkbox,
  Button,
  TextField,
  FormControlLabel,
} from '@material-ui/core';
import api from '../../pages/api';
import { useRouter } from 'next/router';
import { Modal } from 'react-bootstrap';
import NavBar from '../header';
const useStyles = makeStyles((theme) => ({
  box: {
    width: '40%',
    height: 120,
    backgroundColor: '#cecece',
    margin: 20,
    padding: 10,
    borderRadius: 12,
  },

  boxcentral: {
    backgroundColor: '#fff',
    marginLeft: 25,
    width: '100%',
    height: ' 100%',
    marginTop: 30,
  },
}));

export default function Home() {
  const classes = useStyles();
  const [user, setUser] = useState(null);
  const [allTodos, setAllTodos] = useState([]);
  const [title, setTitle] = useState('');
  const [checked, setChecked] = useState(false);
  const [showModal, setShowModal] = useState(false);

  function handleShowModal() {
    setShowModal(!showModal);
  }

  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    getUser();
    getTodos();
  }, []);

  useEffect(() => {
    getUser();
    getTodos();
  }, [id]);

  const handleChange = (event) => {
    setChecked(event.target.checked);
  };

  async function getUser() {
    try {
      const data = await api.get(`users/${id}`);
      setUser(data.data);
    } catch (error) {
      console.log(error);
    }
  }

  async function getTodos() {
    try {
      const data = await api.get(`users/${id}/todos`);
      setAllTodos(data.data);
    } catch (error) {
      console.log(error);
    }
  }

  function ModalAdd() {
    return (
      <Grid>
        <Modal
          show={showModal}
          onHide={handleShowModal}
          style={{
            marginTop: 120,
          }}
        >
          <Modal.Header>
            <Modal.Title>Adicionar um novo usuário</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <TextField
              inputProps={{
                style: { backgroundColor: 'white' },
              }}
              style={{ marginRight: 12 }}
              variant="outlined"
              fullWidth
              placeholder="Type the title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />

            <FormControlLabel
              style={{ marginLeft: 10, marginTop: 10 }}
              control={
                <Checkbox
                  checked={checked}
                  onChange={handleChange}
                  inputProps={{ 'aria-label': 'secondary checkbox' }}
                  color="primary"
                />
              }
              label="Status"
            />
          </Modal.Body>
          <Modal.Footer>
            <Button
              variant="secondary"
              onClick={handleShowModal}
              style={{
                backgroundColor: '#6E6F71',
                color: '#fff',
                fontWeight: 'bold',
                margin: 5,
              }}
            >
              Fechar
            </Button>
            <Button
              variant="primary"
              onClick={() => addNewTodo()}
              style={{
                margin: 5,
                backgroundColor: '#F05026',
                color: '#fff',
                fontWeight: 'bold',
              }}
            >
              Concluir
            </Button>
          </Modal.Footer>
        </Modal>
      </Grid>
    );
  }

  async function addNewTodo() {
    try {
      const newInfo = {
        userId: id,
        id: Math.random * 1000,
        title,
        completed: checked,
      };
      const newTodo = allTodos.concat(newInfo);
      setAllTodos(newTodo);
      setTitle(null);
      setChecked(false);
      handleShowModal();
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <div className={classes.boxcentral}>
      <Head>
        <title>Escola Mais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid>
        <Grid
          style={{
            marginLeft: 30,
            marginTop: 30,
            marginBottom: 30,
            height: 40,
            width: 150,
            backgroundColor: '#F05026',
            borderRadius: 6,
            justifyContent: 'center',
            alignItems: 'center',
            display: 'flex',
          }}
        >
          <a onClick={() => handleShowModal()}>
            <Typography
              variant="span"
              component="span"
              style={{
                color: '#fff',
                textAlign: 'center',
              }}
            >
              <strong>Add Todo</strong>
            </Typography>
          </a>
          {ModalAdd()}
        </Grid>
      </Grid>

      <Grid>
        {allTodos?.map((todo) => {
          return (
            <Grid
              key={todo.id}
              container
              justify="space-between"
              alignItems="center"
              direction="row"
              className={classes.box}
            >
              <Grid item>
                <Typography component="h6" variant="h6" color="inherit">
                  {todo.title}
                </Typography>
                <Checkbox
                  checked={todo.completed}
                  onChange={(event) => event.target.checked}
                  color="primary"
                  inputProps={{ 'aria-label': 'secondary checkbox' }}
                />
              </Grid>
            </Grid>
          );
        })}
      </Grid>
      <div>
        <Button
          href="/"
          style={{
            marginLeft: 50,
            margin: 5,
            backgroundColor: '#242424',
            color: '#fff',
            fontWeight: 'bold',
          }}
        >
          Voltar
        </Button>
      </div>
    </div>
  );
}
