import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { makeStyles } from '@material-ui/core/styles';
import { Container, Grid, Typography } from '@material-ui/core';
import api from '../../pages/api';
import Navbar from '../header';

const useStyles = makeStyles((theme) => ({
  Container: {
    backgroundColor: '#ccc',
  },

  box: {
    width: '20%',
    height: 120,
    marginLeft: 20,
    backgroundColor: '#ddd',
    marginTop: 25,
    margin: 0,
    padding: 10,
    borderRadius: 12,
  },
  appbar: {
    margin: 10,
  },
  boxcentral: {
    backgroundColor: '#fff',
    width: '100%',
    height: ' 100%',
  },
  navbar: {
    margin: 0,
  },
}));

export default function Home() {
  const classes = useStyles();
  const [users, setUsers] = useState([]);

  useEffect(() => {
    getUsers();
  }, []);

  async function getUsers() {
    try {
      const data = await api.get('users');
      setUsers(data.data);
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <div className={classes.boxcentral}>
      <Navbar className={classes.navbar} />
      <Head>
        <title>Escola Mais</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        className={classes.appbar}
        style={{ marginTop: 30, margin: 30 }}
        lg={12}
        container
      >
        {users.map((user) => {
          return (
            <Link
              key={user.id}
              passHref
              href={{
                pathname: '/detalhes',
                query: { id: user.id },
              }}
            >
              <Grid
                container
                justify="space-between"
                alignItems="center"
                direction="row"
                className={classes.box}
              >
                <Grid item>
                  <Typography component="h6" variant="h6" color="inherit">
                    {user.name}
                  </Typography>
                  <Typography component="span" variant="span" color="inherit">
                    {user.email.toLowerCase()}
                  </Typography>
                </Grid>

                <Grid item>
                  <Typography component="span" variant="span" color="inherit">
                    City: <strong>{user.address.city}</strong>
                  </Typography>
                </Grid>
              </Grid>
            </Link>
          );
        })}
      </Grid>
    </div>
  );
}
